-- Update Team

-- !Ups
ALTER TABLE Commitment ALTER a VARCHAR(40000) NOT NULL;
ALTER TABLE Proof ALTER Proof VARCHAR(40000) NOT NULL;

-- !Downs
ALTER TABLE Commitment ALTER a VARCHAR(2000) NOT NULL;
ALTER TABLE Proof ALTER Proof VARCHAR(10000) NOT NULL;
